### ISSUE TITLE
The building instruction is NOT pointing to npmjs

### ISSUE THREAD

**Issue by hsluoyz** [nbudin/react-blockly#15]
This is not the usual way:

```
Clone this repository, and then inside it, do:

npm install
npm run build
```

Everyone will use this instead:

```
npm i react-blockly
```

I really doubt that you even ever dog-food your own code successfully in your React projects.

**Comment by nbudin** [comment]
Hi @hsluoyz; I've updated the README.  The instructions you were seeing before were for building the package source locally (useful for developing on the package), not for installing react-blockly in your own React projects.  I've clarified this and added further instructions above them for using react-blockly in your own project as well as running webpack-dev-server for package development.

> I really doubt that you even ever dog-food your own code successfully in your React projects.

This sort of derogatory language is unhelpful and is not welcome here.  Please refer to the [code of conduct](https://github.com/nbudin/react-blockly/blob/master/CODE_OF_CONDUCT.md) for the project, and please avoid this sort of language here in the future.  Thanks!
