### ISSUE TITLE
Code for languages other than JS not working

### ISSUE THREAD

**Issue by mastanca** [nbudin/react-blockly#16]
When trying to produce code in a language other than JS i get an undefined when calling workspaceToCode() function. Here goes an example using de demo and trying to produce python

```javascript
    workspaceDidChange = (workspace) => {
      workspace.registerButtonCallback('myFirstButtonPressed', () => {
        alert('button is pressed');
      });
      const newXml = Blockly.Xml.domToText(
        Blockly.Xml.workspaceToDom(workspace),
      );
      document.getElementById('generated-xml').innerText = newXml;

      console.log(Blockly);

      const code = Blockly.Python.workspaceToCode(workspace);
      document.getElementById('code').value = code;
    };
```

produces error on browser:

````
Cannot read property 'workspaceToCode' of undefined
````

**Comment by nbudin** [comment]
Interesting - I have a feeling this has to do with something about the npm package build of Blockly that I'm not quite understanding.  In the entry point for the browser package of Blockly, you can see it explicitly setting up the JavaScript code generator but no other languages: https://github.com/google/blockly/blob/master/package/browser/index.js

But I'm kind of unsure of:

1. Where that `BlocklyJS` constant is even coming from in that module
2. How you'd import other code generators in the context of the npm package

**Comment by nbudin** [comment]
Actually, try adding this somewhere in your file:

```javascript
import 'blockly/python.js';
```

(Exact import path/syntax might vary depending on your setup.)  It looks like that file exists in the npm package, and loading it will cause `Blockly.Python` to exist.

**Comment by mastanca** [comment]
That workaround seems to work 👍

**Comment by nbudin** [comment]
Great, glad to hear it!
