### ISSUE TITLE
Define custom category

### ISSUE THREAD

**Issue by foreverzmy** [nbudin/react-blockly#19]
Hello,I want to define custom category, just like [Scratch](https://scratch.mit.edu/projects/editor/?tutorial=getStarted)，how should I do? Thanks.

**Comment by nbudin** [comment]
Hi @foreverzmy, I'm not quite sure if this is what you're asking, but I'm going to assume you want to add some custom blocks and make a category for them in your toolbox.  If this isn't what you wanted, please reply and clarify.

First, you'll want to define some custom blocks.  Google's official Blockly documentation has [a good page about this here](https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks).  In the case of react-blockly, you'll also need to `import Blockly from 'blockly';` near the top of the file where you're defining the custom blocks.

Once you've done that, you should be able to reference them in the `toolboxCategories` prop just like the built-in blocks that come with Blockly (using the `type` field inside the `blocks` objects).  For an example of a custom toolbox category configuration, see the example code here: https://github.com/nbudin/react-blockly/blob/11eb6aff4223e707d1cfa7058fc91f5b9436d91a/src/dev-index.jsx#L23

**Comment by nbudin** [comment]
(Closing this, but if I haven't actually answered your question please feel free to reopen and clarify.)

**Comment by foreverzmy** [comment]
Thanks for your reply。
What I want is change the category dom tree，for [Scratch](https://scratch.mit.edu/projects/editor/?tutorial=getStarted) is 
![](https://user-images.githubusercontent.com/11779129/78316912-731acd00-7593-11ea-9015-6cdd5b609c46.png)

And you can see the dom tree，Under the `.blocklyToolboxDiv` element is `.scratchCategoryMenu`，and in blockly is `.blocklyTreeRoot`。

![image](https://user-images.githubusercontent.com/11779129/78317119-005e2180-7594-11ea-8d68-914ebae8b940.png)

So how to change it? Thanks.
