### ISSUE TITLE
Upgrade to new Google's blockly lib version

### ISSUE THREAD

**Issue by mastanca** [nbudin/react-blockly#23]
As of date there is a [new version](https://github.com/google/blockly/tree/3.20200625.1) of Google's blockly lib. Any thoughts on upgrading?

**Comment by nbudin** [comment]
Seems like a good idea to me!  I'm not sure when I'll get to it but if you want it faster, feel free to open a pull request here?

**Comment by nbudin** [comment]
This is now fixed - thanks for the PR!
