### ISSUE TITLE
Render toolbox without categories

### ISSUE THREAD

**Issue by DuyTungHa** [nbudin/react-blockly#27]
Hi. Do you know how to render a toolbox with no categories - a toolbox that just has blocks on it. 
I have been trying to do it but it doesn't work. Either by modifying the javascript array or modifying the xml string. 
Any ideas ? Thanks.

**Comment by nbudin** [comment]
You can do this by passing the `toolboxBlocks` prop rather than `toolboxCategories` to the Blockly component.
