### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by CodeDoctorDE** [nbudin/react-blockly#28]
I need a package @types/react-blocky which does not exist :D

It will be cool if you add it!

**Comment by nbudin** [comment]
If you want type definitions, another way to go would be to add them right into this package as `index.d.ts`.  I'm not sure I will have a lot of time to work on this myself but if you want to contribute some type definitions, I would be happy to add them to the released package!

**Comment by pelikhan** [comment]
@nbudin i can probably help you with converting react-blockly to TypeScript/rollup.

**Comment by nbudin** [comment]
> @nbudin i can probably help you with converting react-blockly to TypeScript/rollup, now that we use hooks.

That would be awesome.  I'd be more than happy to review and accept PRs for that!

**Comment by nbudin** [comment]
This is now available in version 7.0.0-alpha.2.  Thanks @pelikhan for the initial work on this and thanks @vanmeegen for finishing it up!
