### ISSUE TITLE
componentWillReceiveProps has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by MonkeyInWind** [nbudin/react-blockly#32]
![image](https://user-images.githubusercontent.com/34543887/91995064-ea82a180-ed69-11ea-8568-1c04f9c1d1bc.png)

**Comment by chqboris** [comment]
componentWillReceiveProps = (newProps) => {
    if (this.props.initialXml !== newProps.initialXml) {
      this.setState({ xml: newProps.initialXml });
    }
==>
static getDerivedStateFromProps(nextProps,prevState){
    if (prevState.initialXml !== nextProps.initialXml) {
      return nextProps.initialXml 
    }
    return null
}
