### ISSUE TITLE
Support native JSON toolbox format

### ISSUE THREAD

**Issue by Merlin04** [nbudin/react-blockly#36]
As of the latest Blockly release (September 2020) you can define the toolbox in JSON instead of only XML (see https://developers.google.com/blockly/guides/configure/web/toolbox#json). This format is really similar to `react-blockly`'s format but has more configuration options, like separators. It would be great if `react-blockly` could support this new format.

**Comment by nbudin** [comment]
I would definitely love to add this feature!  I am probably not going to be able to code it soon myself, but would be very happy to accept a PR from someone.
