### ISSUE TITLE
Upgrade Blockly to the latest version (v8.0.3)

### ISSUE THREAD

**Issue by pavi2410** [nbudin/react-blockly#76]
I will open a PR soon. My fork is at https://github.com/KodeForks/react-blockly/tree/react-18

**Comment by nbudin** [comment]
Hi @pavi2410, thanks for reaching out!  I'm not sure what problem this fork is solving.  react-blockly already has a lax version dependency on Blockly so that it will support any version above 3.20200024.0, and React 18 is already supported in react-blockly as well, so it should be possible to use it with Blockly 8.0.3 as it currently stands.  What problem are you running into trying to do this?

**Comment by nbudin** [comment]
Please try the latest version.  It has much fewer direct dependencies on Blockly, and mostly is just a very thing wrapper layer, so I think it should work.

**Comment by pavi2410** [comment]
Just tried now and it error'd.

```
react-blockly: 7.0.1
blockly: 8.0.3
```

```
ERROR in /workspaces/react-blockly/src/useBlocklyWorkspace.ts
./src/useBlocklyWorkspace.ts 75:6-46
[tsl] ERROR in /workspaces/react-blockly/src/useBlocklyWorkspace.ts(75,7)
      TS2345: Argument of type '{ toolbox: Blockly.utils.toolbox.ToolboxDefinition; }' is not assignable to parameter of type '() => void'.
  Object literal may only specify known properties, and 'toolbox' does not exist in type '() => void'.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/index.ts 1:0-56 4:0-49
 @ ./src/dev-index.tsx 26:0-43 69:17-33

webpack 5.63.0 compiled with 1 error in 3968 ms
```

**Comment by pavi2410** [comment]
`yarn.lock` resolves older version of Blockly
```
"blockly@>= 3.20200024.0":
  version "5.20210325.0"
```

**Comment by nbudin** [comment]
Ah, I see what's going on.  It looks like there's a known issue with the TypeScript typings in Blockly 8.x where some types are getting written as `() => void`, and the toolbox definition parameter type is one of them.  See this issue: https://github.com/google/blockly/issues/6215

In the meantime, I would recommend using `// @ts-expect-error` as a workaround.  This should begin working fine once that issue in Blockly is fixed.
