### ISSUE TITLE
ReadOnly option not working under workspaceConfiguration

### ISSUE THREAD

**Issue by sujeithnath** [nbudin/react-blockly#83]
Hi there, 

As the title mentions, when I add readOnly: true, it give me below error 

`Uncaught Error: Existing toolbox is null.  Can't create new toolbox.
    at WorkspaceSvg$$module$build$src$core$workspace_svg.updateToolbox (workspace_svg.ts:1869:13)
    at useBlocklyWorkspace.js:43:23`
    
    
`const {workspace} = useBlocklyWorkspace({
        ref: blocklyRef,
        initialXml: programXml,
        toolboxConfiguration: {
            "kind": "flyoutToolbox",
            "contents": [
                {
                    "kind": "block",
                    "type": "controls_if"
                },
                {
                    "kind": "block",
                    "type": "controls_whileUntil"
                }
            ]
        },
        workspaceConfiguration: {
            renderer: 'crc_renderer',
            readOnly: true,
            scrollbars: true,
            trashcan: false,
            grid: {
                spacing: 20,
                length: 3,
                colour: '#ccc',
                snap: true,
            },
            media: '/blockly/media/',
        },
        onDispose: (ws) => logger.info('on ws dispose', ws),
        // @ts-ignore
        onInject: (ws) => logger.info('injected ws', ws?.undoStack_),
        onWorkspaceChange: (ws) => logger.info('on ws change', ws),
        onImportXmlError: (error) => logger.warn('error importing XML', error)
    })`

**Comment by nbudin** [comment]
Hi @sujeithnath!  I'm not totally sure what's happening with `readOnly`, but one thing I'd recommend trying is to move the `toolboxConfiguration` value into a const _outside your React component_.  This will prevent `useBlocklyWorkspace` from trying to update the workspace on every render cycle.  Could you try that out and let me know if it solves your issue?

**Comment by arontsang** [comment]
@nbudin The syncing code is trying to update the UI element `workspace` with the React prop `workspace`.

However, there is no UI element `workspace`, because `readonly` is set to true.

I've put in a PR for this issue.

**Comment by nbudin** [comment]
Thanks @arontsang!  This PR is merged and I've released v7.3.0 with the fix.
